#!/bin/bash
# This will download all the files needed for a riocar.org offline copy

wget -rk http://www.riocar.org
wget -r http://www.riocar.org/lens/green_indoor.jpg
wget -r http://www.riocar.org/lens/green_ambient.jpg
wget -r http://www.riocar.org/lens/green_fullsun.jpg
wget -r http://www.riocar.org/lens/blue_indoor.jpg
wget -r http://www.riocar.org/lens/blue_ambient.jpg
wget -r http://www.riocar.org/lens/blue_fullsun.jpg
wget -r http://www.riocar.org/lens/amber_indoor.jpg
wget -r http://www.riocar.org/lens/amber_ambient.jpg
wget -r http://www.riocar.org/lens/amber_fullsun.jpg
wget -r http://www.riocar.org/lens/red_indoor.jpg
wget -r http://www.riocar.org/lens/red_ambient.jpg
wget -r http://www.riocar.org/lens/red_fullsun.jpg
wget -r http://www.riocar.org/lens/clear_indoor.jpg
wget -r http://www.riocar.org/lens/clear_ambient.jpg
wget -r http://www.riocar.org/lens/clear_fullsun.jpg
wget -r http://www.riocar.org/lens/smoke_indoor.jpg
wget -r http://www.riocar.org/lens/smoke_ambient.jpg
wget -r http://www.riocar.org/lens/smoke_fullsun.jpg
wget -r http://www.riocar.org/lens/deepblue_indoor.jpg
wget -r http://www.riocar.org/lens/deepblue_ambient.jpg
wget -r http://www.riocar.org/lens/deepblue_fullsun.jpg
wget -r http://www.riocar.org/lens/lightblue_indoor.jpg
wget -r http://www.riocar.org/lens/lightblue_ambient.jpg
wget -r http://www.riocar.org/lens/lightblue_fullsun.jpg
wget -r http://www.riocar.org/lens/deepred_indoor.jpg
wget -r http://www.riocar.org/lens/deepred_ambient.jpg
wget -r http://www.riocar.org/lens/deepred_fullsun.jpg
wget -r http://www.riocar.org/lens/neonred_indoor.jpg
wget -r http://www.riocar.org/lens/neonred_ambient.jpg
wget -r http://www.riocar.org/lens/neonred_fullsun.jpg
wget -r http://www.riocar.org/lens/deepgreen_indoor.jpg
wget -r http://www.riocar.org/lens/deepgreen_ambient.jpg
wget -r http://www.riocar.org/lens/deepgreen_fullsun.jpg
wget -r http://www.riocar.org/lens/neongreen_indoor.jpg
wget -r http://www.riocar.org/lens/neongreen_ambient.jpg
wget -r http://www.riocar.org/lens/neongreen_fullsun.jpg
wget -r http://www.riocar.org/lens/orange_indoor.jpg
wget -r http://www.riocar.org/lens/orange_ambient.jpg
wget -r http://www.riocar.org/lens/orange_fullsun.jpg
